contact_links:
  - name: plugins.Textpattern.com website issue
    url: https://github.com/textpattern/textpattern-plugins-website/issues/new?template=report-a-website-issue.md
    about: Create a report to help us improve the Textpattern plugin website (not specifically related to a plugin listing).
